### ISSUE TITLE
no restart after reboot

### ISSUE THREAD

**Issue by leiweke** [Saharel001/dbus-ksem#1]
Hello, many Thanks für this great program.
I had a issue that the program did not restart after reboot, therefore I run
ln -s /data/dbus-ksem/service /service/dbus-ksem
and also added it to the /data/rc.local
ln -s /data/dbus-ksem/service /service/dbus-ksem

I do not know if this it the right way, but it works for me ;-)

Many Thanks
Sebastian

**Comment by Saharel001** [comment]
Hi, thanks i fix it in the next days

**Comment by Saharel001** [comment]
fix with https://github.com/Saharel001/dbus-ksem/commit/e9b8eb0f5a80cd1be75ccd67a8cb51a4d3fa65dd

**Comment by leiweke** [comment]
Perfect it's working fine. Thanks for the fix.
